fsf_2019_screening_task1/TasKManager/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'TasKManager'

urlpatterns = [path('', views.loginPage, name="login"),
               path('signup/', views.signUpPage, name="signup"),
               path('welcome/', views.welcomePage, name="welcomepage"),
               # path('invitations/', include('invitations.urls', namespace='invitations')),
               path('welcome/createteams/', views.createTeam, name="createTeams"),
               path('welcome/createteams/<int:pk>/', views.TeamListView, name= "teamList"),


    ]

fsf_2019_screening_task1/fsf_2019_screening_task1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('TasKManager.urls'))
]

fsf_2019_screening_task1/TasKManager/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class SignUp(models.Model):
    username = models.CharField(max_length=100)
    email_id = models.EmailField(max_length=100)
    mobile_no = models.IntegerField()
    password = models.CharField(max_length=40)
    confrom_pass = models.CharField(max_length=40)

    def __str__(self):
        return self.username


class Task(models.Model):
    status_choice = (
        ('INPROGRESS', 'Inprogress'), ('NOT ASSIGNED', 'Not assigned'), ('DONE', 'done'), ('PLANNED', 'Planned'))
    id = models.AutoField(primary_key=True)
    Title = models.CharField(max_length=150)
    Description = models.TextField(blank=True)
    Assignee = models.ForeignKey(SignUp, on_delete=models.CASCADE)
    Status = models.CharField(choices=status_choice, default='NOT ASSIGNED', blank=False, max_length=50)
    Time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.Title, self.Assignee


class Team(models.Model):
    Creator_name = models.ForeignKey(SignUp, on_delete=models.CASCADE, related_name='teams')
    Team_Name = models.CharField(max_length=100)
    members = models.ManyToManyField(SignUp)
    description = models.TextField(max_length=1024,blank=True)
    created_date = models.DateTimeField(default=timezone.now)

    # logo = models.ImageField(blank=True)
    def __str__(self):
        return self.Team_Name

fsf_2019_screening_task1/TasKManager/forms.py
from django import forms
from .models import SignUp, Team


class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), required=True)
    confrom_pass = forms.CharField(widget=forms.PasswordInput(), required=True)

    class Meta:
        model = SignUp
        fields = '__all__'


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), required=True)

    class Meta:
        model = SignUp
        fields = ['email_id', 'password']


class CreateTeam(forms.ModelForm):
    class Meta:
        creator_name = forms.CharField
        model = Team
        fields = '__all__'

fsf_2019_screening_task1/TasKManager/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from . import forms
from django.views import generic
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from .models import SignUp, Team
from django.views.generic import (TemplateView, ListView, DeleteView, DetailView, CreateView, UpdateView)
from django.utils import timezone



class TeamListView(ListView):
    print("h")
    template_name='TasKManager/index.html'

    def get_queryset(self):
       print("df")
       return Team.objects.all()
 
def loginPage(request):
    if request.method == 'POST':
        obj = forms.LoginForm(request.POST)
        if obj.is_valid():
            model = SignUp
            Email = obj.cleaned_data['email_id']
            Password = obj.cleaned_data['password']
            typed_email = ''
            typed_pass = ''
            try:
                typed_email = model.objects.filter(email_id=Email).only("email").values_list()[0][2]
                typed_pass = model.objects.filter(password=Password).only("email").values_list()[0][4]
                typed_email = str(typed_email)
                typed_pass = str(typed_pass)
            except:
                pass

            if Email == typed_email and Password == typed_pass:
                print("entered in box")
                return render(request, 'afterLogin.html', {'email': Email})
            else:
                return HttpResponse("<h2>User may not exist , please signUp first</h2>")
    else:
        obj = forms.LoginForm()
        return render(request, 'base.html', {'obj': obj})


def signUpPage(request):
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email_id = form.cleaned_data['email_id']
            mobile_no = form.cleaned_data['mobile_no']
            password = form.cleaned_data['password']
            confrom_pass = form.cleaned_data['confrom_pass']
            form.save(commit=True)
            return HttpResponse("<h2>Hey congo you created your account</h2>")
    else:
        form = forms.SignUpForm()
        return render(request, 'signup.html', {'form': form})


# @login_required
def welcomePage(request):
    return render(request, 'afterLogin.html', None)


def createTeam(request):
    form = forms.CreateTeam
    return render(request, 'createTeam.html', {'form': form})


# function that will display team list

fsf_2019_screening_task1/fsf_2019_screening_task1/views.py
from django.views.generic import (TemplateView, ListView, DeleteView, DetailView, CreateView, UpdateView)
from django.shortcuts import render, get_object_or_404, redirect


def LoginPage(request):
    return render(request, 'base.html', context=None)

fsf_2019_screening_task1/TasKManager/templates/TasKManager/index.html
{%  extends 'base.html' %}

{% block content %}
{% for Team in object_list %}
            <div class="post">
                <div class="date">
                    <p>Team Name{{ post.Team_Name}}</p>
                </div>
                    <h1><a href="{% url 'TasKManager:detail' Team.id %}">{{ Team.description}}</a></h1>
                    <p>{{ Team.text|linebreaksbr }}</p>

            </div>
{% endfor %}
{% endfor %}
{% endblock %}

fsf_2019_screening_task1/TasKManager/templates/TasKManager/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<nav class="navbar navbar-default techfont custom-navbar">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand bigbrand" href="#">My Blog</a></li>
            <li><a href="#">About</a></li>
            <li><a href="https://github.com" target="_blank">GitHub Login</a></li>
            <li><a href="http://linkedin.com/in" target="_blank">LinkedIn</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="#">New Post</a></li>
            <li><a href="#">Drafts</a></li>
            <li><a href="#">Logout</a></li>
            <li><a> welcome : {{ user.username }}</a></li>

            {% else %}
            <li><a class="nav navbar-right" href="#"><span class="glyphicon glyphicon-user"></span>Login</a>
            </li>
            {% endif %}
        </ul>
    </div>

</nav>
</body>
</html>

fsf_2019_screening_task1/TasKManager/templates/afterLogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome page</title>
{% load staticfiles %}


    <style>
        * {
            margin: 0;
            padding: 0;
            -webkit-box-sizing: border-box;
            box-sizing: border-box;
        }
        h1 {
            font-size: 2.5rem;
            font-family: 'Montserrat';
            font-weight: normal;
            color: #444;
            text-align: center;
            margin: 2rem 0;
        }
        .wrapper {
            width: 90%;
            margin: 0 auto;
            max-width: 80rem;
        }
        .cols {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            -ms-flex-wrap: wrap;
            flex-wrap: wrap;
            -webkit-box-pack: center;
            -ms-flex-pack: center;
            justify-content: center;
        }
        .col {
            width: calc(25% - 2rem);
            margin: 1rem;
            cursor: pointer;
        }
        .container {
            -webkit-transform-style: preserve-3d;
            transform-style: preserve-3d;
            -webkit-perspective: 1000px;
            perspective: 1000px;
        }
        .front,
        .back {
            background-size: cover;
            background-position: center;
            -webkit-transition: -webkit-transform .7s cubic-bezier(0.4, 0.2, 0.2, 1);
            transition: -webkit-transform .7s cubic-bezier(0.4, 0.2, 0.2, 1);
            -o-transition: transform .7s cubic-bezier(0.4, 0.2, 0.2, 1);
            transition: transform .7s cubic-bezier(0.4, 0.2, 0.2, 1);
            transition: transform .7s cubic-bezier(0.4, 0.2, 0.2, 1), -webkit-transform .7s cubic-bezier(0.4, 0.2, 0.2, 1);
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;
            text-align: center;
            min-height: 280px;
            height: auto;
            border-radius: 10px;
            color: #fff;
            font-size: 1.5rem;
        }
        .back {
            background: #cedce7;
            background: -webkit-linear-gradient(45deg, #cedce7 0%, #596a72 100%);
            background: -o-linear-gradient(45deg, #cedce7 0%, #596a72 100%);
            background: linear-gradient(45deg, #cedce7 0%, #596a72 100%);
        }
        .front:after {
            position: absolute;
            top: 0;
            left: 0;
            z-index: 1;
            width: 100%;
            height: 100%;
            content: '';
            display: block;
            opacity: .6;
            background-color: #000;
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;
            border-radius: 10px;
        }
        .container:hover .front,
        .container:hover .back {
            -webkit-transition: -webkit-transform .7s cubic-bezier(0.4, 0.2, 0.2, 1);
            transition: -webkit-transform .7s cubic-bezier(0.4, 0.2, 0.2, 1);
            -o-transition: transform .7s cubic-bezier(0.4, 0.2, 0.2, 1);
            transition: transform .7s cubic-bezier(0.4, 0.2, 0.2, 1);
            transition: transform .7s cubic-bezier(0.4, 0.2, 0.2, 1), -webkit-transform .7s cubic-bezier(0.4, 0.2, 0.2, 1);
        }
        .back {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
        }
        .inner {
            -webkit-transform: translateY(-50%) translateZ(60px) scale(0.94);
            transform: translateY(-50%) translateZ(60px) scale(0.94);
            top: 50%;
            position: absolute;
            left: 0;
            width: 100%;
            padding: 2rem;
            -webkit-box-sizing: border-box;
            box-sizing: border-box;
            outline: 1px solid transparent;
            -webkit-perspective: inherit;
            perspective: inherit;
            z-index: 2;
        }
        .container .back {
            -webkit-transform: rotateY(180deg);
            transform: rotateY(180deg);
            -webkit-transform-style: preserve-3d;
            transform-style: preserve-3d;
        }
        .container .front {
            -webkit-transform: rotateY(0deg);
            transform: rotateY(0deg);
            -webkit-transform-style: preserve-3d;
            transform-style: preserve-3d;
        }
        .container:hover .back {
            -webkit-transform: rotateY(0deg);
            transform: rotateY(0deg);
            -webkit-transform-style: preserve-3d;
            transform-style: preserve-3d;
        }
        .container:hover .front {
            -webkit-transform: rotateY(-180deg);
            transform: rotateY(-180deg);
            -webkit-transform-style: preserve-3d;
            transform-style: preserve-3d;
        }
        .front .inner p {
            font-size: 2rem;
            margin-bottom: 2rem;
            position: relative;
        }
        .front .inner p:after {
            content: '';
            width: 4rem;
            height: 2px;
            position: absolute;
            background: #C6D4DF;
            display: block;
            left: 0;
            right: 0;
            margin: 0 auto;
            bottom: -.75rem;
        }
        .front .inner span {
            color: rgba(255, 255, 255, 0.7);
            font-family: 'Montserrat';
            font-weight: 300;
        }
        @media screen and (max-width: 64rem) {
            .col {
                width: calc(33.333333% - 2rem);
            }
        }
        @media screen and (max-width: 48rem) {
            .col {
                width: calc(50% - 2rem);
            }
        }
        @media screen and (max-width: 32rem) {
            .col {
                width: 100%;
                margin: 0 0 2rem 0;
            }
        }
    </style>
</head>
<body>
<div class="container">
    <h3> Hi {{email}}</h3>
    <div class="row">

        <div class="container-fluid">
            <div class="col-lg-12 col-md-4 col-sm-4">

                <div class="wrapper">

                    <div class="cols">
                        <div class="col" ontouchstart="this.classList.toggle('hover');">
                            <div class="container">
                                <div class="front" style="background-image: url(https://unsplash.it/500/500/)">
                                    <div class="inner">
                                        <p> Craete Team</p>
                                        <span>Craete, Assign & manage team </span>
                                    </div>
                                </div>
                                <div class="back">
                                    <div class="inner">
                                        <p>create your own team, as a leader adding task to your team.</p>
                                        <button type="button" class="btn btn-default">
                                            <a href="{% url 'TasKManager:createTeams' %}">click here</a>
                                        </button>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="col" ontouchstart="this.classList.toggle('hover');">
                            <div class="container">
                                <div class="front" style="background-image: url(https://unsplash.it/503/503/)">
                                    <div class="inner">
                                        <p>Join Team</p>
                                        <span>Be a Part of Someone's Team</span>
                                    </div>
                                </div>
                                <div class="back">
                                    <div class="inner">
                                        <p>Join a team and take task which suits you more </p>
                                        <button type="button" class="btn btn-default">click here</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
</div>

</body>
</html>

fsf_2019_screening_task1/TasKManager/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load bootstrap3 %}
<head>
    <meta charset="UTF-8">
    <title>{%block title%} Welcome page {%endblock%}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load staticfiles %}
    <!-- Optional theme -->


    <!-- Latest compiled and minified JavaScript -->

    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css'%}">
    <link rel="script" href="{% static 'javascript/login.js'%}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Mukta');
        body {
            font-family: 'Mukta', sans-serif;
            height: 100vh;
            min-height: 850px;
            background-image: url(http://www.planwallpaper.com/static/images/Free-Wallpaper-Nature-Scenes.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center;
            position: relative;
            overflow-y: hidden;
            padding-top: 350px;
        }
        a {
            text-decoration: none;
            color: #444444;
        }
        .login-reg-panel {
            position: relative;
            top: 50%;
            transform: translateY(-50%);
            text-align: center;
            width: 70%;
            right: 0;
            left: 0;
            margin: auto;
            height: 400px;
            background-color: rgba(236, 48, 20, 0.9);
        }
        .white-panel {
            background-color: rgba(255, 255, 255, 1);
            height: 500px;
            position: absolute;
            top: -50px;
            width: 50%;
            right: calc(50% - 50px);
            transition: .3s ease-in-out;
            z-index: 0;
            box-shadow: 0 0 15px 9px #00000096;
        }
        .login-reg-panel input[type="radio"] {
            position: relative;
            display: none;
        }
        .login-reg-panel {
            color: #B8B8B8;
        }
        .login-reg-panel #label-login,
        .login-reg-panel #label-register {
            border: 1px solid #9E9E9E;
            padding: 5px 5px;
            width: 150px;
            display: block;
            text-align: center;
            border-radius: 10px;
            cursor: pointer;
            font-weight: 600;
            font-size: 18px;
        }
        .login-info-box {
            width: 30%;
            padding: 0 50px;
            top: 20%;
            left: 0;
            position: absolute;
            text-align: left;
        }
        .register-info-box {
            width: 30%;
            padding: 0 50px;
            top: 20%;
            right: 0;
            position: absolute;
            text-align: left;
        }
        .right-log {
            right: 50px !important;
        }
        .login-show,
        .register-show {
            z-index: 1;
            display: none;
            opacity: 0;
            transition: 0.3s ease-in-out;
            color: #242424;
            text-align: left;
            padding: 50px;
        }
        .show-log-panel {
            display: block;
            opacity: 0.9;
        }
        .login-show input[type="text"], .login-show input[type="password"] {
            width: 100%;
            display: block;
            margin: 20px 0;
            padding: 15px;
            border: 1px solid #b5b5b5;
            outline: none;
        }
        .login-show input[type="button"] {
            max-width: 150px;
            width: 100%;
            background: #444444;
            color: #f9f9f9;
            border: none;
            padding: 10px;
            text-transform: uppercase;
            border-radius: 2px;
            float: right;
            cursor: pointer;
        }
        .login-show a {
            display: inline-block;
            padding: 10px 0;
        }
        .register-show input[type="text"], .register-show input[type="password"] {
            width: 100%;
            display: block;
            margin: 20px 0;
            padding: 15px;
            border: 1px solid #b5b5b5;
            outline: none;
        }
        .register-show input[type="button"] {
            max-width: 150px;
            width: 100%;
            background: #444444;
            color: #f9f9f9;
            border: none;
            padding: 10px;
            text-transform: uppercase;
            border-radius: 2px;
            float: right;
            cursor: pointer;
        }
        .credit {
            position: absolute;
            bottom: 10px;
            left: 10px;
            color: #3B3B25;
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            text-transform: uppercase;
            font-size: 12px;
            font-weight: bold;
            letter-spacing: 1px;
            z-index: 99;
        }
        a {
            text-decoration: none;
            color: #2c7715;
        }
    </style>


    <script>
        $(document).ready(function () {
            $('.login-info-box').fadeOut();
            $('.login-show').addClass('show-log-panel');
        });
        $('.login-reg-panel input[type="radio"]').on('change', function () {
            if ($('#log-login-show').is(':checked')) {
                $('.register-info-box').fadeOut();
                $('.login-info-box').fadeIn();
                $('.white-panel').addClass('right-log');
                $('.register-show').addClass('show-log-panel');
                $('.login-show').removeClass('show-log-panel');
            }
            else if ($('#log-reg-show').is(':checked')) {
                $('.register-info-box').fadeIn();
                $('.login-info-box').fadeOut();
                $('.white-panel').removeClass('right-log');
                $('.login-show').addClass('show-log-panel');
                $('.register-show').removeClass('show-log-panel');
            }
        });
    </script>

    <!--google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat+Alternates" rel="stylesheet">
</head>

<body>
<div class="container-fluid">
    <div class="center">
        <div class="">
            <div class="login-reg-panel">
                <div class="login-info-box">
                    <label id="label-register" for="log-reg-show">Login</label>
                    <input type="radio" name="active-log-panel" id="log-reg-show" checked="checked">

                </div>

                <div class="register-info-box">
                    <h2>Don't have an account?</h2>
                    <p>Try to Register First</p>
                    <!--<button type="button" label id="label-login" a href="{% url 'TasKManager:signup' %}">Register</button>-->
                    <button class="button" label id="label-login">
                        <a href="{% url 'TasKManager:signup' %}">Register</a>
                    </button>
                    <input type="radio" name="active-log-panel" id="log-login-show">
                </div>

                <div class="white-panel">
                    <div class="login-show">
                        <form class="form-horizontal" method="POST" action="#">
                            <h2>LOGIN</h2>
                            {% csrf_token %}
                            {% bootstrap_form obj %}

                            <button type="submit" class="btn btn-success" value="login" style="margin-left: 270px">
                                Login
                            </button>
                            <a href="">Forgot password?</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

fsf_2019_screening_task1/TasKManager/templates/createTeam.html
<!DOCTYPE html>
<html lang="en">
{%load staticfiles %}
{% load bootstrap3 %}
<head>
    <meta charset="UTF-8">
    <title>Create Team page</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
<div class="container">
  <div class="nav bar">
      <h2><center>HI TEAM ENTER DETAILS HERE!</center></h2>
  </div>
    <form class="form-horizontal" method="post" action="#">

        <div class="form-group">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="form-group ">
                <button type="submit" class="btn btn-primary btn-lg btn-block login-button">
				<a href="">Submit
                </button>
            </div>
        </div>
		
		 
    </form>
</div>
</body>
</html>

fsf_2019_screening_task1/TasKManager/templates/index.html
{%  extends 'base.html' %}

{% block content %}
{% for Team in object_list %}
            <div class="post">
                <div class="date">
                    <p>Team Name{{ Team.Team_Name}}</p>
                </div>
                    <h1><a href="{% url 'TasKManager:detail' Team .id %}">{{ Team.description}}</a></h1>
                    <p>{{ Team.text|linebreaksbr }}</p>

            </div>
{% endfor %}
{% endfor %}
{% endblock %}

fsf_2019_screening_task1/TasKManager/templates/signup.html
<!DOCTYPE html>
<html lang="en">
{%load staticfiles %}
{% load bootstrap3 %}
<head>
    <meta charset="UTF-8">
    <title>Sign-up form</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script>
        function validatePassword(password) {
            // Do not show anything when the length of password is zero.
            if (password.length === 0) {
                document.getElementById("msg").innerHTML = "";
                return;
            }
            // Create an array and push all possible values that you want in password
            var matchedCase = new Array();
            matchedCase.push("[$@$!%*#?&]"); // Special Charector
            matchedCase.push("[A-Z]");      // Uppercase Alpabates
            matchedCase.push("[0-9]");      // Numbers
            matchedCase.push("[a-z]");     // Lowercase Alphabates
            // Check the conditions
            var ctr = 0;
            for (var i = 0; i < matchedCase.length; i++) {
                if (new RegExp(matchedCase[i]).test(password)) {
                    ctr++;
                }
            }
            // Display it
            var color = "";
            var strength = "";
            switch (ctr) {
                case 0:
                case 1:
                case 2:
                    strength = "Very Weak";
                    color = "red";
                    break;
                case 3:
                    strength = "Medium";
                    color = "orange";
                    break;
                case 4:
                    strength = "Strong";
                    color = "green";
                    break;
            }
            document.getElementById("msg").innerHTML = strength;
            document.getElementById("msg").style.color = color;
        }
    </script>
</head>
<body>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Register</div>
                <div class="card-body">

                    <form class="form-horizontal" method="post" action="#">

                        <div class="form-group">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <div class="form-group ">
                                <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Register
                                </button>
                            </div>
                        </div>

                        <div class="login-register">
                            <a href="{% url 'TasKManager:login' %}">Login</a>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
</body>
</html>

fsf_2019_screening_task1/TasKManager/templates/teamList.html
{%  extends 'base.html' %}

{% block content %}
{% for Team in object_list %}
            <div class="post">
                <div class="date">
                    <p>Team Name{{ Team.Team_Name}}</p>
                </div>
                    <h1><a href="{% url 'TasKManager:detail' Team .id %}">{{ Team.description}}</a></h1>
                    <p>{{ Team.text|linebreaksbr }}</p>

            </div>
{% endfor %}
{% endfor %}
{% endblock %}